version: '3.8'

services:
  backend:
    # Utilise l'image stockée sur le registre GitLab
    image: ${CI_REGISTRY_IMAGE}/backend:latest
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-network

  frontend:
    image: ${CI_REGISTRY_IMAGE}/frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge