version: '3.8'

services:
  backend:
    image: ${CI_REGISTRY_IMAGE}/backend:latest
    restart: always
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=staging
    networks:
      - portfolio-network

  frontend:
    image: ${CI_REGISTRY_IMAGE}/frontend:latest
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge